name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  sveltekit:
    name: SvelteKit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build SvelteKit
        run: npm run build
        env: ${{ secrets }}
  histoire:
    name: Histoire
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build Histoire
        run: npm run story:build