name: Playwright Test

on:
  push:
    branches: ["main", "env/prod", "env/dev"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Run Playwright tests
        run: npm run test:e2e