name: Playwright Test

on:
  push:
    branches: ["main", "env/prod", "env/dev"]
  pull_request:
    types: [opened, synchronize]

jobs:
  end-to-end:
    name: End-to-end
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30